GTPARSER_PREFIX   ?= $(if $(OSTYPE_UNIX),/usr,C:/devel)
GTPARSER_INCLUDE  ?= $(GTPARSER_PREFIX)/include
GTPARSER_LIBDIR   ?= $(GTPARSER_PREFIX)/lib
GTPARSER_LIB_NAME ?= gtparser
LIBGTPARSER_S     ?= $(LIB_PREFIX)$(GTPARSER_LIB_NAME)$(call LIB_VAR_SUFFIX,S)$(LIB_SUFFIX)
SYSINCLUDE += $(GTPARSER_INCLUDE)
SYSLIBS    += $(call qpath,$(call ospath,$(GTPARSER_LIBDIR)/$(LIBGTPARSER_S)))
