GTPARSER_PREFIX   ?= /usr
GTPARSER_INCLUDE  ?= $(GTPARSER_PREFIX)/include
GTPARSER_LIBDIR   ?= $(GTPARSER_PREFIX)/lib
GTPARSER_LIB_NAME ?= gtparser
LIBGTPARSER       ?= $(LIB_PREFIX)$(GTPARSER_LIB_NAME)$(LIB_SUFFIX)
INCLUDE += $(GTPARSER_INCLUDE)
SYSLIBS += $(GTPARSER_LIBDIR)/$(LIBGTPARSER)
