MEMSTACK_PREFIX  ?= /usr
MEMSTACK_INCLUDE ?= $(MEMSTACK_PREFIX)/include
MEMSTACK_LIBDIR  ?= $(MEMSTACK_PREFIX)/lib
LIBMEMSTACK      ?= libmemstack$(if $(DEBUG),d).so
ifdef DEBUG
DEFINES += MEMSTACK_DEBUG
endif
DEFINES += MEMSTACK_EXPORTS=$(DLL_IMPORTS_DEFINE)
INCLUDE += $(MEMSTACK_INCLUDE)
SYSLIBS += $(MEMSTACK_LIBDIR)/$(LIBMEMSTACK)
