MEMSTACK_PREFIX  ?= /usr
MEMSTACK_INCLUDE ?= $(MEMSTACK_PREFIX)/include
MEMSTACK_LIBDIR  ?= $(MEMSTACK_PREFIX)/lib
LIBMEMSTACK      ?= libmemstack$(if $(DEBUG),d)$(call DEP_LIB_SUFFIX,$(LIBMEMSTACK_VARIANT)).a
LIBMEMSTACK_VARIANT
ifdef DEBUG
DEFINES += MEMSTACK_DEBUG
endif
INCLUDE += $(MEMSTACK_INCLUDE)
SYSLIBS += $(MEMSTACK_LIBDIR)/$(LIBMEMSTACK)
