MEMSTACK_PREFIX  ?= /usr
MEMSTACK_INCLUDE ?= $(MEMSTACK_PREFIX)/include
MEMSTACK_LIBDIR  ?= $(MEMSTACK_PREFIX)/lib
LIBMEMSTACK      ?= libmemstack$(if $(DEBUG),d).a
ifdef DEBUG
DEFINES += MEMSTACK_DEBUG
endif
INCLUDE += $(MEMSTACK_INCLUDE)
SYSLIBS += $(MEMSTACK_LIBDIR)/$(LIBMEMSTACK)
