ifndef MAKE_JAVA_EVAL
include $(dir $(lastword $(MAKEFILE_LIST)))/../../../config.mk
endif
$(MAKE_JAVA_EVAL)
JAR     := bitbridge
JSRC    := bitbridge/BridgePriv.java bitbridge/Bridge.java
$(DEFINE_TARGETS)
