GTPARSER_INCLUDE ?= $(GTPARSER_PREFIX)/include
GTPARSER_LIBDIR  ?= $(GTPARSER_PREFIX)/lib
LIBGTPARSER      ?= libgtparser_S.a
INCLUDE += $(GTPARSER_INCLUDE)
SYSLIBS += $(GTPARSER_LIBDIR)/$(LIBGTPARSER)
