ifndef GTPARSER_INCLUDE
GTPARSER_INCLUDE := $(GTPARSER_PREFIX:=/include)
endif
ifndef GTPARSER_LIBDIR
GTPARSER_LIBDIR := $(GTPARSER_PREFIX:=/lib)
endif
ifndef GTPARSER_INCLUDE
$(error GTPARSER_INCLUDE or GTPARSER_PREFIX not defined!)
endif
ifndef GTPARSER_LIBDIR
$(error GTPARSER_LIBDIR or GTPARSER_PREFIX not defined!)
endif
LIBGTPARSER ?= libgtparser.a
INCLUDE     += $(GTPARSER_INCLUDE)
SYSLIBS     += $(GTPARSER_LIB)/$(LIBGTPARSER)
